---
- name: AWS - Delete infrastructure
  hosts: localhost

  tasks:

    - name: Delete VPC
      register: aws_vpc
      amazon.aws.ec2_vpc_net:
        state: absent
        name: "{{ my_aws_vpc }}"
    
    - name: Delete internet gateway
      register: aws_gateway
      amazon.aws.ec2_vpc_igw:
        state: absent
        vpc_id: "{{ aws_vpc.vpc.id }}"
        region: "{{ my_aws_region }}"
        tags:
          Name: "{{ my_aws_vpc }}-vpc-igw"
          owner: "{{ my_aws_vpc }}"
      
    - name: Delete security group internal
      amazon.aws.ec2_group: 
        state: anbsent
        name: "{{ my_aws_vpc }}-sec-group"
        region: "{{ my_aws_region }}"
        vpc_id: "{{ aws_vpc.vpc.id }}"
        tags:
          Name: "{{ my_aws_vpc }}-sec-group"
          owner: "{{ my_aws_vpc }}"
    
    - name: Delete a subnet on the VPC
      register: aws_subnet
      amazon.aws.ec2_vpc_subnet:
        state: absent
        vpc_id: "{{ aws_vpc.vpc.id }}"
        cidr: "{{ my_aws_vpc_cidr }}"
        region: "{{ my_aws_region }}"
        map_public: yes
        tags:
          Name: "{{ my_aws_vpc }}-subnet"
          owner: "{{ my_aws_vpc }}"
    
    - name: Delete a subnet route table 
      amazon.aws.ec2_vpc_route_table:
        state: absent 
        vpc_id: "{{ aws_vpc.vpc.id }}"
        region: "{{ my_aws_region }}"
        subnets:
          - "{{ aws_subnet.subnet.id }}"
        tags: 
          Name: "{{ my_aws_vpc }}-vpc-rtbl"
          owner: "{{ my_aws_vpc }}"

    - name: Delete AWS keypair
      amazon.aws.ec2_key:
        name: "{{ my_aws_vpc }}-demo-key"
        region: "{{ my_aws_region }}"
        key_material: "{{ lookup('file', '{{ my_aws_public_key }}') }}"  #"{{ my_aws_public_key }}"
        state: absent
        tags:
          owner: "{{ my_aws_vpc }}"